name: dbt CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  dbt_transformation:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_TOKEN_PROJ_1: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      DATABRICKS_TOKEN_UAT: ${{ secrets.DATABRICKS_TOKEN_UAT }}
      DATABRICKS_TOKEN_PROD: ${{ secrets.DATABRICKS_TOKEN_PROD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-databricks

      # BƯỚC QUAN TRỌNG: Copy profiles.yml vào đúng nơi dbt mặc định tìm kiếm (~/.dbt/profiles.yml)
      - name: Setup dbt profiles directory
        run: |
          mkdir -p ~/.dbt
          cp ./Project_Sales/profiles.yml ~/.dbt/profiles.yml

      # 1. Step cho DEV (Pull Request)
      - name: Run dbt for DEV (Pull Request)
        if: github.event_name == 'pull_request'
        working-directory: ./Project_Sales
        run: |
          dbt deps
          dbt build --target dev

      # 2. Step cho UAT (Push to Main)
      - name: Run dbt for UAT (Push to Main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./Project_Sales
        run: |
          dbt deps
          dbt build --target uat

      # 3. Step cho PROD (Git Tag)
      - name: Run dbt for PROD (Git Tag)
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./Project_Sales
        run: |
          dbt deps
          dbt build --target prod
